services:

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:aalimous
    
    env_file:
      - .env
    volumes:
      - data_wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - Inception
    restart: on-failure

  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    image: nginx:aalimous
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - data_wordpress:/var/www/wordpress
    networks:
      - Inception
    restart: on-failure
  mariadb:
    build: requirements/mariadb
    image: mariadb:aalimous
  
    env_file:
      - .env
    volumes:
      - data_mariadb:/var/lib/mysql
    networks:
      - Inception
    restart: on-failure
    

volumes:
  data_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aalimous/data/wordpress'
  data_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aalimous/data/mariadb'
networks:
  Inception: